name: paperlessngx_uploader
description: "A Flutter app for uploading documents to Paperless-NGX via Android share intent"
publish_to: 'none'

version: 1.7.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.35.1"

dependencies:
  flutter:
    sdk: flutter
  # Flutter official localizations
  flutter_localizations:
    sdk: flutter
  # Internationalization/formatting (pinned to match Flutter SDK requirement)
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  
  # HTTP client for API calls
  http: ^1.2.2
  dio: ^5.5.0
  
  # Secure storage for credentials
  flutter_secure_storage: ^9.2.4
  
  # Share intent handling
  receive_sharing_intent: ^1.8.1
  
  # File handling
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # State management
  provider: ^6.1.2
  
  # UI components
  flutter_typeahead: ^5.2.0

  # Toast notifications
  fluttertoast: ^8.2.12

  # App info and version checking
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.5
  device_info_plus: ^11.1.1

  # URL launching
  url_launcher: ^6.3.1

  # Permission handling
  permission_handler: ^12.0.1
  # Desktop drag & drop support for Windows/Linux/macOS
  desktop_drop: ^0.6.1
  # Desktop window sizing helpers
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  generate: true
