name: paperless_ngx_android_uploader
description: "A Flutter app for uploading documents to Paperless-NGX via Android share intent"
publish_to: 'none'

version: 1.2.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
  
dependencies:
  flutter:
    sdk: flutter
  # Flutter official localizations
  flutter_localizations:
    sdk: flutter
  # Internationalization/formatting (pinned to match Flutter SDK requirement)
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  
  # HTTP client for API calls
  http: ^1.2.2
  dio: ^5.5.0
  
  # Secure storage for credentials
  flutter_secure_storage: ^9.2.4
  
  # Share intent handling
  receive_sharing_intent: ^1.8.1
  
  # File handling
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # State management
  provider: ^6.1.2
  
  # UI components
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  generate: true
